### PR TITLE
Make Calendar component mobile-friendly

### LINKED ISSUE #2140: Fractional booking does not work on mobile
Reproduction steps:
 - Open Origin mobile app
 - Go to purchase page for a fractional listing
 - Try to select checkin date on calendar
=> Nothing happens

### PR DESCRIPTION
**Pull request by shahthepro**
Closes #2140 and #1217

### CODE REVIEW

**Comment by tomlinton** [comment]
@nick did you have a chance to take a look a this? Do we want to take a different approach? It'd be cool to get this solved, I can look into it if we want to go a different way.

**Comment by nick** [comment]
After talking to Aure we want to switch to a 'click for start date, then click for end date' instead of the 'click and drag for range' we have currently. That should solve the mobile issue I think

**Comment by shahthepro** [comment]
@tomlinton  @nick 

> After talking to Aure we want to switch to a 'click for start date, then click for end date'

Have updated the component to support this behaviour on mobile. 

Still dates across months cannot be selected. That's on my to-do list. But that should not be a blocking issue. We can raise that as a separate issue.

**Comment by nick** [comment]
Since we changed from the original idea of dragging on mobile, I was able to simplify the diff somewhat...

**Pull request merged**
