### PR TITLE
Alternative to polling for balance updates

### PR DESCRIPTION
**Pull request by mikeshultz**
### Description:

This uses "strategic" events to update the balance instead of an interval to poll for balance updates.  Currently this includes sending transactions and changing networks.

Anything I'm missing?

### Checklist:

- [ ] Test your work and double-check to confirm that you didn't break anything
- [ ] [Wrap any new text/strings with `fbt`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#wrapping-text) for translation
- [ ] If there are any new/changed strings to translate, [`npm run translate`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#integrating-translations)
- [ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/docs)

### CODE REVIEW

**Comment by tomlinton** [comment]
Is there any reason to ditch polling? As far as I can tell this doesn't cover the case where someone is staring at the Origin wallet and tries to send OGN to it from MetaMask, it'll never update without some intervention.

**Comment by mikeshultz** [comment]
The reason is a reduction in JSON-RPC requests. Having it infinitely ask for balance updates is expensive(especially ERC20 balance checks).

That's an interesting use case.  Wonder if a refresh button(or pull down) is reasonable addition for this.  Or maybe just add polling when the wallet page is displayed.  Though I don't know if the latter is possible since the nav seems to not unmount pages after their initial display.

Suggestions?

**Comment by tomlinton** [comment]
This should work for polling on focus only https://reactnavigation.org/docs/en/3.x/with-navigation-focus.html

**Comment by mikeshultz** [comment]
Awesome, that seems to do the trick.  Updated so it'll poll every 10s when a user is eyeballing their balances.  

I'm kind of wondering if this is the only place a balance update should occur(when a user is looking at the wallet screen).  Though it'll take 10s for the first interval to hit so I think I'll leave the other event emitters.

**Pull request merged**
