### PR TITLE
Purse: Fixes logic for using @origin/web3-provider

### PR DESCRIPTION
**Pull request by mikeshultz**
### Description:

Fixes a logic bug which appears to have prevented Purse from using our custom web3 provider.

### Checklist:

- [ ] Test your work and double-check to confirm that you didn't break anything
- [ ] [Wrap any new text/strings with `fbt`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#wrapping-text) for translation
- [ ] If there are any new/changed strings to translate, [`npm run translate`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#integrating-translations)
- [ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/docs)

### CODE REVIEW

**Comment by mikeshultz** [comment]
It's broken, don't merge this yet if you were thinking about it.

**Comment by franckc** [comment]
I hear you. I'll let you merge when you are ready...

**Comment by mikeshultz** [comment]
@franckc this includes the unit test for that pending check.  Seems to work fine...

**Comment by mikeshultz** [comment]
I take that back, this doesn't work fine at all...

**Comment by franckc** [comment]
@mikeshultz Some relevant tests are failing. PTAL before merging...

**Comment by mikeshultz** [comment]
okay, this actually fixes the bug causing that check to fail!  And tests are working again.  Will merge shortly and move on to deploy.

**Pull request merged**
