### PR TITLE
New prelink url open upon notification

### PR DESCRIPTION
**Pull request by crazybuster**
First pull request? Read our [guide to contributing](http://docs.originprotocol.com/#contributing)

### Description:

Please explain the changes you made here:

Send notification upon offer and prelink safari against the wallet.

### Checklist:

- [ ] Test your work and double-check to confirm that you didn't break anything
- [ ] Wrap any displayed ETH addresses with [`formattedAddress`](https://github.com/OriginProtocol/origin/blob/master/origin-dapp/src/utils/user.js#L15-L17)
- [ ] Wrap any new text/strings for translation
- [ ] Map any new environment variables with a default value in the Webpack config
- [ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/origin-docs)

### CODE REVIEW

**Comment by micahalcorn** [comment]
Let's Gauge This Mess 😬

**Comment by micahalcorn** [comment]
@crazybuster @tomlinton I'm getting this when I try to run master after merging this PR:

```bash
origin:origin micah$ npm run install:mobile

> root@ install:mobile /Users/micah/buidl/origin
> npm install --ignore-scripts && npm run bootstrap:mobile

npm WARN eslint-config-react-app@3.0.5 requires a peer of babel-eslint@9.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@3.0.5 requires a peer of eslint-plugin-flowtype@2.x but none is installed. You must install peer dependencies yourself.

audited 37338 packages in 5.711s
found 0 vulnerabilities


> root@ bootstrap:mobile /Users/micah/buidl/origin
> lerna bootstrap --progress --scope origin-linking --scope origin-mobile --scope origin --scope origin-contracts --scope origin-dapp --scope origin-messaging --scope origin-discovery --scope origin-notifications

lerna notice cli v3.5.1
lerna info versioning independent
lerna info filter [ 'origin-linking',
lerna info filter   'origin-mobile',
lerna info filter   'origin',
lerna info filter   'origin-contracts',
lerna info filter   'origin-dapp',
lerna info filter   'origin-messaging',
lerna info filter   'origin-discovery',
lerna info filter   'origin-notifications' ]
lerna info Bootstrapping 8 packages
lerna info Symlinking packages and binaries
lerna info lifecycle origin-contracts@0.8.6~prepare: origin-contracts@0.8.6

> origin-contracts@0.8.6 prepare /Users/micah/buidl/origin/origin-contracts
> npm run build


> origin-contracts@0.8.6 build /Users/micah/buidl/origin/origin-contracts
> per-env


> origin-contracts@0.8.6 build:development /Users/micah/buidl/origin/origin-contracts
> truffle compile contracts

Error: Cannot find module 'typedarray-to-buffer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/micah/buidl/origin/origin-contracts/node_modules/web3-providers-ws/node_modules/websocket/lib/W3CWebSocket.js:18:16)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! origin-contracts@0.8.6 build:development: `truffle compile contracts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the origin-contracts@0.8.6 build:development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/micah/.npm/_logs/2018-12-31T19_36_51_501Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! origin-contracts@0.8.6 build: `per-env`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the origin-contracts@0.8.6 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/micah/.npm/_logs/2018-12-31T19_36_51_606Z-debug.log
lerna info lifecycle origin-contracts@0.8.6~prepare: Failed to exec prepare script
lerna ERR! lifecycle "prepare" errored in "origin-contracts", exiting 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! root@ bootstrap:mobile: `lerna bootstrap --progress --scope origin-linking --scope origin-mobile --scope origin --scope origin-contracts --scope origin-dapp --scope origin-messaging --scope origin-discovery --scope origin-notifications`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the root@ bootstrap:mobile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/micah/.npm/_logs/2018-12-31T19_36_51_646Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! root@ install:mobile: `npm install --ignore-scripts && npm run bootstrap:mobile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the root@ install:mobile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/micah/.npm/_logs/2018-12-31T19_36_51_669Z-debug.log
```

**Comment by micahalcorn** [comment]
I was able to resolve this in the past by resetting origin-contracts/package-lock.json to an older commit but can't now.

**Comment by tomlinton** [comment]
This is web3, there is beta 37 out that should resolve these packaging issues but I know @crazybuster had problems with beta 36 so was sticking to beta 34. You want to test out beta 37 or want me to upgrade to it and see what happens?

**Comment by tomlinton** [comment]
I ran an install without issue, committed the `package-lock.json` files that got generated to a branch [here](https://github.com/OriginProtocol/origin/tree/tomlinton/mobile-package-locks). The issue is intermittent so perhaps I just got lucky with my install.

Related:

#1007 
#1009

**Comment by tomlinton** [comment]
I just saw a comment on the issue on the web3.js repo that beta 37 doesn't resolve this 😞

**Comment by micahalcorn** [comment]
@tomlinton your successful installation was with `install` or `install:mobile`? In my prior experience, I was able to `install` fine but could only `install:mobile` with an older -contracts/package-lock. I think mine currently fails consistently but I'll keep trying.

**Comment by tomlinton** [comment]
It was with `install:mobile`, log:

```
➜  kubernetes git:(master) npm run clean                   (gke_origin-214503_us-west1-a_origin/dev)

> root@ clean /Users/tom/Code/origin
> git clean -fdX .

Removing deployment/kubernetes/values/origin/secrets-dev.yaml
Removing experimental/origin-admin/node_modules/
Removing experimental/origin-dapp2/node_modules/
Removing experimental/origin-eventsource/node_modules/
Removing experimental/origin-graphql-simple-demo/node_modules/
Removing experimental/origin-graphql/node_modules/
Removing experimental/origin-messaging-client/node_modules/
Removing ipfs-proxy/node_modules/
Removing node_modules/
Removing origin-contracts/build/
Removing origin-contracts/node_modules/
Removing origin-dapp-creator-client/node_modules/
Removing origin-dapp-creator-server/node_modules/
Removing origin-dapp/node_modules/
Removing origin-discovery/node_modules/
Removing origin-faucet/node_modules/
Removing origin-js/node_modules/
Removing origin-messaging/node_modules/
Removing origin-notifications/node_modules/
Removing origin-tests/node_modules/
Removing origin-token-transfer/client/node_modules/
```

```
➜  origin git:(master) npm run install:mobile              (gke_origin-214503_us-west1-a_origin/dev)

> root@ install:mobile /Users/tom/Code/origin
> npm install --ignore-scripts && npm run bootstrap:mobile

added 757 packages from 779 contributors and audited 37338 packages in 6.618s
found 0 vulnerabilities


> root@ bootstrap:mobile /Users/tom/Code/origin
> lerna bootstrap --progress --scope origin-linking --scope origin-mobile --scope origin --scope origin-contracts --scope origin-dapp --scope origin-messaging

lerna notice cli v3.5.1
lerna info versioning independent
lerna info filter [ 'origin-linking',
lerna info filter   'origin-mobile',
lerna info filter   'origin',
lerna info filter   'origin-contracts',
lerna info filter   'origin-dapp',
lerna info filter   'origin-messaging' ]
lerna info Bootstrapping 6 packages
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna info lifecycle origin-contracts@0.8.6~prepare: origin-contracts@0.8.6

> origin-contracts@0.8.6 prepare /Users/tom/Code/origin/origin-contracts
> npm run build


> origin-contracts@0.8.6 build /Users/tom/Code/origin/origin-contracts
> per-env


> origin-contracts@0.8.6 build:development /Users/tom/Code/origin/origin-contracts
> truffle compile contracts

Compiling ./contracts/Migrations.sol...
Compiling ./contracts/identity/ClaimHolder.sol...
Compiling ./contracts/identity/ClaimHolderLibrary.sol...
Compiling ./contracts/identity/ClaimHolderPresigned.sol...
Compiling ./contracts/identity/ClaimHolderRegistered.sol...
Compiling ./contracts/identity/ClaimVerifier.sol...
Compiling ./contracts/identity/ERC725.sol...
Compiling ./contracts/identity/ERC735.sol...
Compiling ./contracts/identity/IdentityEvents.sol...
Compiling ./contracts/identity/KeyHolder.sol...
Compiling ./contracts/identity/KeyHolderLibrary.sol...
Compiling ./contracts/identity/OriginIdentity.sol...
Compiling ./contracts/identity/V00_UserRegistry.sol...
Compiling ./contracts/marketplace/v00/Marketplace.sol...
Compiling ./contracts/token/OriginToken.sol...
Compiling ./contracts/token/TestToken.sol...
Compiling ./contracts/token/TokenMigration.sol...
Compiling ./contracts/token/WhitelistedPausableToken.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/lifecycle/Pausable.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/math/SafeMath.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/ownership/Ownable.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/token/ERC20/BasicToken.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/token/ERC20/BurnableToken.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/token/ERC20/DetailedERC20.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/token/ERC20/ERC20.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/token/ERC20/ERC20Basic.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/token/ERC20/MintableToken.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/token/ERC20/PausableToken.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/token/ERC20/StandardToken.sol...
Writing artifacts to ./build/contracts

lerna success Bootstrapped 6 packages
```

**Comment by tomlinton** [comment]
It looks like the `package-lock.json` files that got committed in #1131 are broken. I think what happened is I didn't have them locally when I did that above install. The dev deployment for `origin-messaging` is getting similar errors to what you had above.

**Pull request merged**
