### PR TITLE
River/split listing detail component

### PR DESCRIPTION
**Pull request by riverfor**
I have fixed the "split listing detail component (#237)" issue.

### CODE REVIEW

**Comment by riverfor** [comment]
Thanks, I will try to merge master into my branch and submit it again.

**Comment by micahalcorn** [comment]
@riverfor thanks for revisiting this. I made a commit to remove your package-related changes, which didn't appear to be necessary.

Somehow, your branch re-implements a different photos layout for the listing detail page. Can you follow up and resolve that change to work with your new component structure?

**Old:** `river/split_listing_detail_component`

screen shot 2018-11-28 at 3 45 06 pm

**New:** `master`

screen shot 2018-11-28 at 3 45 42 pm

**Comment by riverfor** [comment]
> @riverfor thanks for revisiting this. I made a commit to remove your package-related changes, which didn't appear to be necessary.
> 
> Somehow, your branch re-implements a different photos layout for the listing detail page. Can you follow up and resolve that change to work with your new component structure?
> 
> **Old:** `river/split_listing_detail_component`
> 
> screen shot 2018-11-28 at 3 45 06 pm
> 
> **New:** `master`
> 
> screen shot 2018-11-28 at 3 45 42 pm

Sure, I will update it as soon.

**Comment by riverfor** [comment]
Please have a look, I have made some improvements. @micahalcorn

**Comment by micahalcorn** [comment]
@riverfor why all the formatting adjustments? 😕 Did you run a format command or something? But it also seems that the `OfferRemark` code style is not consistent with the rest of origin-dapp.

**Comment by riverfor** [comment]
@micahalcorn Sorry, I used a new editor with improper configuration, I have corrected the mistake, please have a look.

**Comment by micahalcorn** [comment]
Thanks @riverfor 🙏 I’ll take a look soon.

**Pull request merged**
