### PR TITLE
[EventListener] Index contract events

### PR DESCRIPTION
**Pull request by franckc**
First pull request? Read our [guide to contributing](http://docs.originprotocol.com/#contributing)

### Checklist:

- [X] Test your work and double-check to confirm that you didn't break anything
- [X] Ensure all new and existing tests pass
- [X] Format code to be consistent with the project
- [ ] Wrap any new text/strings for translation
- [ ] Map any new environment variables with a default value in the Webpack config
- [ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/origin-docs)

### Description:
Store events emitted by marketplace contracts into a new Postgres "event" table.
Use cases for this data:
 - history of activity on Listings and Offers: useful for analytics but also when investigating engineering issues/bugs
 - power some DApp features via the back-end rather than web3 calls. For example to fetch notifications that are shown in the DApp, see marketplace.getNotifications method.

### CODE REVIEW

**Comment by sparrowDom** [comment]
Nice, didn't know of `padStart` function. Pretty useful thing. LGTM, just have 1 thought:

would it make sense to also add `logIndex` into the Postgres table this way we could select events in this manner: `SELECT * FROM event ORDER BY blockNumber, logIndex` to replay events in chronological order.

**Comment by franckc** [comment]
@sparrowDom The id field stores a concatenation of <blockNumber>-<logIndex> (with numbers padded to keep ordering). To get the logs in chronological order we can then just do:
`SELECT * FROM event ORDER BY id`

**Comment by sparrowDom** [comment]
A right, thanks!

**Comment by franckc** [comment]
Yeah, you guys are right. It is simpler to just use a composite pk (blockNumber, logIndex). Thanks for the suggestion. Let me update the schema...

**Pull request merged**
