### PR TITLE
[WIP] Bridge: Implement a route for logging events in the DB

### PR DESCRIPTION
**Pull request by franckc**
### Description:

Implemented a new route /utils/log for the bridge that can be called by the DApp to log any kind of event into a new "log" DB table. The plan is to use that to instrument the DApp core transaction flow.

Still WIP since I want to work a bit on the DApp side instrumentation (as a separate PR) to determine if the log table schema is good enough.

### Checklist:

- [X] Test your work and double-check to confirm that you didn't break anything
- [ ] [Wrap any new text/strings with `fbt`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#wrapping-text) for translation
- [ ] If there are any new/changed strings to translate, [`npm run translate`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#integrating-translations)
- [ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/docs)

### CODE REVIEW

**Comment by tomlinton** [comment]
Sentry has support for capturing other non-exception data too. Might not be suitable but might be worth checking out.

**Comment by franckc** [comment]
@tomlinton Yes, thanks for pointing the possibility of capturing Events with tags using Sentry.
For context, I'm thinking using this logging to track the various steps in the purchase transaction flow. So that for example we can get the percentage of success/failure at various stages in the pipeline.
Sentry's capabilities for querying event data are limited. Afaict it only provides a search with filters.  I'm thinking having events in the DB will be more versatile to analyze the data.
But let me work a bit on the purchase flow instrumentation in the DApp to understand better the data we'll track before making a final decision...

**Comment by tomlinton** [comment]
Yep it won't really work well if we are wanting to do structured queries. As you note in the PR we might need to make the schema more transaction specific to be able to get nicer queries.

**Comment by franckc** [comment]
Abandoning this since it is no longer a priority.

**Pull request closed without merging**
