### PR TITLE
Allowing loading Dshop in iframes

### PR DESCRIPTION
**Pull request by shahthepro**
Dshop's theme editor loads the preview in an iframe.

### CODE REVIEW

**Review by tomlinton — APPROVED** [review]

**Review by franckc — APPROVED** [review]
LGTM

**Comment by shahthepro** [comment]
@mikeshultz Unfortunately, this didn't work. I'm not sure if I'm missing something. Let me know if you happen to know something about this issue.

**Comment by mikeshultz** [comment]
This image doesn't have a cloudbuild process at all and has to be done manually.  I'll roll this within the hour starting with staging.

**Comment by mikeshultz** [comment]
Deployed on staging but this doesn't appear to completely enable it.  Will see what I can figure out.  Seen this when testing:

    Refused to display 'https://rinkebyapi.ogn.app/theme/art/?shop=mikes-swag' in a frame because it set 'X-Frame-Options' to 'deny'

**Comment by mikeshultz** [comment]
Updated `X-Frame-Options` in PR #4513 and testing on staging looks good.  Will roll to prod shortly.

**Comment by shahthepro** [comment]
Thanks for fixing this @mikeshultz

**Pull request merged**
