### PR TITLE
Remove old file-based hidden/featured

### PR DESCRIPTION
**Pull request by DanielVF**
Our new moderation happens directly on the discovery server. We no longer need to fetch hidden or featured files from GitHub. This removes a bit of code related to this from our dapps, GraphQL, and discovery server.

### CODE REVIEW

**Comment by DanielVF** [comment]
Yes, I confirmed with Kay and Austin that they did not need a specific order to featured listings.

**Comment by franckc** [comment]
Thanks for confirming. I'll merge this PR once the meta-tx release is a bit more stable...

**Comment by DanielVF** [comment]
Yeah, makes plenty of sense to wait.

**Comment by franckc** [comment]
@nick @sparrowDom I'm going to merge this in unless there is any objection...

**Comment by sparrowDom** [comment]
nice cleanup 👍

**Pull request merged**
