### PR TITLE
[Growth] Misc fixes and improvements to payout script

### PR DESCRIPTION
**Pull request by franckc**
First pull request? Read our [guide to contributing](https://docs.originprotocol.com/guides/getting_started/contributing.html)

### Description:

 - Add support for gas price multiplier
 - Improve dry-run mode
 - Fix import in token package that prevented loading the OriginToken contract

### Checklist:

- [X] Test your work and double-check to confirm that you didn't break anything
- [ ] [Wrap any new text/strings with `fbt`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#wrapping-text) for translation
- [ ] If there are any new/changed strings to translate, [`npm run translate`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#integrating-translations)
- [ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/docs)

### CODE REVIEW

**Comment by franckc** [comment]
Merging this in so that I can start the payout. Will integrate any feedback as a separate PR...

**Comment by franckc** [comment]
ooooohhh good catch @sparrowDom ! Will add the latest symlink. THANK YOU :)

**Comment by franckc** [comment]
Oh. Actually it did get added. See https://github.com/OriginProtocol/origin/tree/master/packages/contracts/releases

**Comment by sparrowDom** [comment]
Yeah I just saw the `packages/contracts/releases/latest` being added as a new file in diff and didn't understand what that is. Is that how symlink is displayed in diff?

**Comment by franckc** [comment]
Yeah, it is a symlink. And the funny thing is that I thought it would not be added to the repo because I did not run git add on it. But apparently as long as the synlink points to a file already added to the repo, you don't need to do that...

**Pull request merged**
