### PR TITLE
Performance fix for identity card

### PR DESCRIPTION
**Pull request by mikeshultz**
### Description:

Basically, this pulls the unnecessary web3 cruft from the GraphQL `Identity` query so it doesn't use the local resolvers.  I don't really know how Apollo makes all its decisions, but apparently since the Web3 types are local-only, the entire query executes locally instead of remote.  I thought schema stitching was a bit more intelligent, but I suppose not in this case.

In this PR, I only added a new query(`SkinnyIdentity`) as opposed to rewriting the previous because I only wanted to clear (#2716).  However, this specific issue will probably impact other identity loads in other parts of the dapp.  On top of that, there are a lot of queries similar to this one that are run locally because they're crafted in such a way that forces Apollo to route them locally.  This is probably something that should be kept in mind in the future by dapp devs, and perhaps worthy of a project in the near future.

Performance mode is having relatively low impact right now because of it.  Though at least the heavyweights like `AllListings` seem to still be getting sent to the graphql server.

This also shamlessly includes a change to `@origin/services` to fix the graphql server port so the dapp can actually use performance mode with a local docker setup.

cc @micahalcorn 

### Checklist:

- [x] Test your work and double-check to confirm that you didn't break anything
- [ ] [Wrap any new text/strings with `fbt`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#wrapping-text) for translation
- [ ] If there are any new/changed strings to translate, [`npm run translate`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#integrating-translations)
- [ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/docs)

### CODE REVIEW

**Comment by mikeshultz** [comment]
I'm assuming the failing marketplace tests are not related.  Or at least I can't figure how the profile nav card could have an effect on listing purchases.  /shrug

**Comment by nick** [comment]
I think the tests are failing because graphql/src/configs/test.js has the graphql server pointing at port 4007.

I guess the problem with flaky tests is that we assume new changes aren't the cause when sometimes they are. I'll have another pass at fixing the flaky tests... especially since the Marketplace tests are arguably the most important as they test all parts of the system together.

Trying to remember why it was port 4007 instead of 4002 in services in the first place...

**Comment by mikeshultz** [comment]
> I think the tests are failing because graphql/src/configs/test.js has the graphql server pointing at port 4007.

Doh, I'll change up that config as well for this PR.

> I guess the problem with flaky tests is that we assume new changes aren't the cause when sometimes they are.

Truth.  How did you ID this issue?  Another problem I have with these tests is I don't seem to get any visibility into them(errors, traces) to tell me what went wrong.  Occasionally I'll get more detail locally, but when I ran them locally I just got a different random selection of tests failing silently.

**Comment by mikeshultz** [comment]
Fixed the config... there's still a graphql network error in the tests.  hrm.

**Comment by mikeshultz** [comment]
No network errors on that second run, just a ton of timeouts.

**Comment by nick** [comment]
Just lint now...

**Comment by mikeshultz** [comment]
All green

**Pull request merged**
