### PR TITLE
Android pull to refresh fix

### PR DESCRIPTION
**Pull request by sparrowDom**
### Description:

The problem is that on Android we need to find within webView if user swiping down should allow of the trigger of refresh. The documentElement.scrollTop does not report the scroll position of modal elements. 

For this reason every 500ms a function is executed that finds all scrollable elements and checks their scrollTop value. The maximum of those numbers is reported, and only once all are 0 the refresh on swipe down is enabled.

Works in all cases tested except when: 
 - user opens `all messages` and has them scrolled a bit down
 - then opens a specific message conversation and scrolls around. The scroll down when on top here doesn't work, because the background `all messages` element is not at `scrollTop` position `0`.

Since the above case prevents the reload, it should be an ok compromise.

**Related issue:** https://github.com/OriginProtocol/origin/issues/3360#event-2633586472
### Checklist:

- [x] Test your work and double-check to confirm that you didn't break anything
- [ ] [Wrap any new text/strings with `fbt`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#wrapping-text) for translation
- [ ] If there are any new/changed strings to translate, [`npm run translate`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#integrating-translations)
- [ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/docs)

### CODE REVIEW

**Comment by tomlinton** [comment]
This looks great @sparrowDom, thanks for doing it, it looks like it was a headache. Will spin it up on Android and test it out today or tomorrow!

**Comment by tomlinton** [comment]
Works great thanks @sparrowDom. I ran the injected JavaScript through a linter, just to make it consistent. Also changed the react Component to a PureComponent to reduce the number of renders. It was causing a lot of renders for some reason.

This does introduce some weirdness with the onboarding modal, if you refresh and then hit the back arrow, it'll display again when you try and navigate somewhere. Maybe because of the date we inject into the URL to force refresh on Android. I'll make an issue and we can deal with this in a separate PR though.

**Comment by tomlinton** [comment]
Ref https://github.com/OriginProtocol/origin/issues/3741

**Comment by sparrowDom** [comment]
Nice thanks for the linting and testing Tom.

**Pull request merged**
