### PR TITLE
[ISSUE-2933] Fix floating footer so that it doesn't block `Send Message Button`

### PR DESCRIPTION
**Pull request by wperingbart**
#2769 # Description:

Please explain the changes you made here:

- Floating footer was blocking `Send Message Button` in the chat box.
- Floating footer was too long in text. Removing the text so that it just shows ellipses. Actually it's not greatly helpful to have the text (user would want to click that and notice immediately what it is without any text in it).

### Checklist:

- [x] Test your work and double-check to confirm that you didn't break anything
- [x] [Wrap any new text/strings with `fbt`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#wrapping-text) for translation
- [x] If there are any new/changed strings to translate, [`npm run translate`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#integrating-translations)
- [x] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/docs)

### CODE REVIEW

**Comment by micahalcorn** [comment]
No @franckc, I would prefer that this change be route-specific so that we keep the copy in place most of the time. See https://www.airbnb.com 🙁

**Comment by franckc** [comment]
@wperingbart See comments from @micahalcorn above... he is our product manager so he rules when it comes to user experience decisions ! :) Do you mind updating this PR so that it is route specific and only applies to the messaging route ? Thank you !

**Comment by wperingbart** [comment]
sure @franckc @micahalcorn

**Comment by wperingbart** [comment]
hi @franckc @micahalcorn 
I updated PR.
pls check it and let me know

**Comment by wperingbart** [comment]
have you reviewed this @micahalcorn ?

**Comment by franckc** [comment]
Merged in master. Nice work @wperingbart !

**Pull request merged**
