### PR TITLE
Messaging Account Detection

### PR DESCRIPTION
**Pull request by micahalcorn**
This solves an issue of the "messaging requirement" modal persisting while Orbit is being synced. Now we will start by querying the central server for whether or not the account is in the global registry. We will still listen for it to be enabled later once everything is synced.

### CODE REVIEW

**Comment by micahalcorn** [comment]
This basically combines https://github.com/OriginProtocol/origin/pull/982 & https://github.com/OriginProtocol/origin/pull/1100.

**Comment by micahalcorn** [comment]
@tomlinton this will need a DApp environment variable for the messaging server.

**Comment by tomlinton** [comment]
> @tomlinton this will need a DApp environment variable for the messaging server.

MESSAGING_URL to the express server you created? e.g. `https://messaging-api.staging.originprotocol.com/`?

**Comment by micahalcorn** [comment]
@tomlinton yes, we will need one for production too if it's not already up. This is basically a hotfix for the broken messaging requirement that is plaguing everyone.

**Comment by tomlinton** [comment]
Also requires CORS to be enabled from DApp to that URL by the looks of it. The production one isn't up yet, I'll get the DNS setup.

**Comment by micahalcorn** [comment]
@tomlinton I naively added the CORS piece to get it to work on my machine. It is basically the same as the rules that we had committed in the notifications server. Feel free to tighten it up. 🙏

**Pull request merged**
