### PR TITLE
New type for unitsTotal since it can go negative

### PR DESCRIPTION
**Pull request by crazybuster**
First pull request? Read our [guide to contributing](http://docs.originprotocol.com/#contributing)

### Description:

Please explain the changes you made here:

- Made an assumption that unitsTotal can be uint, apparently not the case.

### Checklist:

- [ ] Test your work and double-check to confirm that you didn't break anything
- [ ] Wrap any displayed ETH addresses with [`formattedAddress`](https://github.com/OriginProtocol/origin/blob/master/origin-dapp/src/utils/user.js#L15-L17)
- [ ] Wrap any new text/strings for translation
- [ ] Run `npm run translations` if there are any changes to translated strings
- [ ] Map any new environment variables with a default value in the Webpack config
- [ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/origin-docs)

### CODE REVIEW

**Comment by Natasha08** [comment]
@crazybuster I manually tested locally, still getting the same error.

**Comment by Natasha08** [comment]
Did a `lerna clean` and it's working for me now

**Comment by franckc** [comment]
I'm lost :) Under what scenario would unitsTotal be negative ??

**Comment by franckc** [comment]
Oh, I now see @Natasha08 's comment now on Discord regarding unitsTotal being negative for services listing...

**Pull request merged**
