### PR TITLE
Smaller welcome message on mobile devices

### PR DESCRIPTION
**Pull request by sparrowDom**
### Description:

Welcome message on mobile devices takes up less vertical space now and is expandable when clicked on.

### Checklist:

- [x] Test your work and double-check to confirm that you didn't break anything
- [x] Wrap any new text/strings for translation
- ~[ ] Map any new environment variables with a default value in the Webpack config~
- ~[ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/origin-docs)~

**Fixes issue:** https://github.com/OriginProtocol/origin/issues/934

**Open Zepplin designs:**
https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5bd24ee31311fc09c26a2484
https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5bd24ee513f4bb09f4dfbda9

Looks like this: 
screenshot 2018-11-21 19 02 02
screenshot 2018-11-21 19 02 08

### CODE REVIEW

**Comment by sparrowDom** [comment]
@micahalcorn sure don't hold back, I want to improve my CSS coding so all comments are welcome.

**Comment by micahalcorn** [comment]
@sparrowDom ah, I was referring more to pixel-perfection than the code. 👌

**Comment by sparrowDom** [comment]
Aha ok, glad to hear things I miss there too.

**Comment by sparrowDom** [comment]
FYI @micahalcorn part of the profile improvements on mobile have [corrected the vertical position](https://github.com/OriginProtocol/origin/commit/d7b7ec6da3b50f81834548aa267fcc78eaa8a100) of the "beta" tag in warning welcome message. Now it looks like this: 
screenshot 2018-11-27 15 48 20
screenshot 2018-11-27 15 48 07
screenshot 2018-11-27 15 50 33

Please let me know if there is anything else that seems out of place. 😇

**Comment by micahalcorn** [comment]
Cool, thx @sparrowDom 💙

**Pull request merged**
