### PR TITLE
Navigation Clarification

### PR DESCRIPTION
**Pull request by micahalcorn**
### Description:

This addresses https://github.com/OriginProtocol/origin/issues/1699 by moving the links from the "Sell" dropdown into the top-level nav on larger screens. It also renames "Buy" to "My Purchases" and drops the "My" and "Earn" across all links when screen width is limited.

### Checklist:

- [x] Test your work and double-check to confirm that you didn't break anything 😕
- [x] [Wrap any new text/strings with `fbt`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#wrapping-text) for translation
- [x] If there are any new/changed strings to translate, [`npm run translate`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#integrating-translations)
- [ ] ~Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/docs)~

### CODE REVIEW

**Comment by nick** [comment]
image

image

**Comment by micahalcorn** [comment]
@nick what browser is that? I was pretty sure I handled those in mine.

**Comment by nick** [comment]
Chrome on OSX

**Comment by micahalcorn** [comment]
@nick 😕 https://www.loom.com/share/4804b1c3d62949fda8ceeb50bc5c5fab

**Comment by micahalcorn** [comment]
Wait, why do you have a blockchain confirmation dropdown and I don't?

**Comment by micahalcorn** [comment]
Ah, I'm missing an icon if my marketplace contract is not found. I'll clean it up @nick.

**Comment by micahalcorn** [comment]
@nick this should be fixed now. It won't be great on more verbose languages, but I think I'll punt that to #405 since these are not common screen widths.

**Pull request merged**
