### PR TITLE
TICKET-3223 allow more listing editing fix

### PR DESCRIPTION
**Pull request by mahamat**
This is a fix for https://github.com/OriginProtocol/origin/issues/3223. 
After checking out the code, it turned out that `Edit and Delete` buttons were available only for items with listing status `active`.  With this change, `Edit and Delete` actions are available for Active and Sold items. 

### Checklist:

- [x ] Test your work and double-check to confirm that you didn't break anything
- [ ] [Wrap any new text/strings with `fbt`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#wrapping-text) for translation
- [ ] If there are any new/changed strings to translate, [`npm run translate`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#integrating-translations)
- [ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/docs)

### CODE REVIEW

**Comment by micahalcorn** [comment]
Thanks @mahamat 👍 Let me know if you're able to deploy a test build and link to it from [here](https://originprotocol.github.io/test-builds/).

**Comment by mahamat** [comment]
> Thanks @mahamat 👍 Let me know if you're able to deploy a test build and link to it from [here](https://originprotocol.github.io/test-builds/).

Yes, sure, working on it. @micahalcorn

**Comment by mahamat** [comment]
> Thanks @mahamat 👍 Let me know if you're able to deploy a test build and link to it from [here](https://originprotocol.github.io/test-builds/).

Deployed test build [here](https://originprotocol.github.io/test-builds/maha), @micahalcorn

**Comment by micahalcorn** [comment]
@mahamat I think I'm still missing an edit link in My Listings for [4-000-929](https://originprotocol.github.io/test-builds/maha/#/listing/4-000-929), which is in a pending state. We should probably handle that one too. 🙂

**Comment by mahamat** [comment]
> @mahamat I think I'm still missing an edit link in My Listings for [4-000-929](https://originprotocol.github.io/test-builds/maha/#/listing/4-000-929), which is in a pending state. We should probably handle that one too. 🙂

Yes, sure, i will update the pr. There is also one `withdrawn` https://originprotocol.github.io/test-builds/maha/#/listing/4-000-302 listing. Should we include it too ?

**Comment by mahamat** [comment]
@micahalcorn , if in pending state, `Pending
An offer has been made on this listing`, should owner be able to edit the item at all ?

**Pull request merged**
