### PR TITLE
Mario blanco/detect local storage

### PR DESCRIPTION
**Pull request by MarioBlanco**
## Description:

Detect if local storage is available. If it's not the app won't work so we show a message box.

Please explain the changes you made here:

a simple function in javascript to detect if we can use local storage, try to save a variable then delete if, if we go through the catch it's because local storage is forbidden 

- A description of the problem you're trying to solve

Detect if the app will crash because we can't use local storage.

- An overview of the suggested solution

### Checklist:

- [x] Test your work and double-check to confirm that you didn't break anything
- [x] [Wrap any new text/strings with `fbt`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#wrapping-text) for translation
- [x] If there are any new/changed strings to translate, [`npm run translate`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#integrating-translations)
- [x] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/docs)

### CODE REVIEW

**Comment by franckc** [comment]
Thanks @MarioBlanco ! This Brave detection issue ended up being a bit more involved than we originally thought :) Would you be able to upload a test build following [these instructions](https://github.com/OriginProtocol/test-builds) to make it easier for folks to test your changes ? Thanks in advance !

**Comment by MarioBlanco** [comment]
Yeah no problem. I liked the evolving issue so far :)

**Comment by MarioBlanco** [comment]
BTW I have done the build

https://originprotocol.github.io/test-builds/testLocalStorage/

Next times I will do it before summiting the PR, thanks for your suggestion.

**Comment by micahalcorn** [comment]
Thanks @MarioBlanco 👍 It's not necessary on every PR, but it helps more of us test front-end changes in different environments.

**Comment by tomlinton** [comment]
Closing due to inactivity.

**Pull request closed without merging**
