### PR TITLE
Natasha/DApp2-- search results

### PR DESCRIPTION
**Pull request by Natasha08**
### Description:
 [Test Build (I used Kovan when I tested)](https://originprotocol.github.io/test-builds/natasha/)

- add listing search to dapp2
- search by:
  - category (i.e. For Rent, For Sale)
  - sub category (i.e. Housing, Clothing and Accessories)
  - price
- This PR does behave differently than the the origin-dapp in different ways, but I thought this was a good point to PR and flesh out issues
  - Combination of filters sometimes do not behave as expected...
  - Price filtering ^
- disabled for mobile users

- [x] Double check Translations

### Checklist:

- [x] Test your work and double-check to confirm that you didn't break anything
- [x] Wrap any new text/strings for translation
- [x] Run `npm run translations` if there are any changes to translated strings

### Screenshots
image
image

### CODE REVIEW

**Comment by Natasha08** [comment]
After getting feedback from Domen, I’m going to update this PR.

**Comment by Natasha08** [comment]
@nick this is ready for a review. Unfortunately I think you have to test this locally, but I'm building to test-builds anyway

**Comment by nick** [comment]
Hey Natasha - I think we probably need to revisit search filtering after we release dapp2 as I think this approach may be overly complex. I appreciate it's how we did things in dapp1 but with the work Stan is doing on ListingTypes I think there could be a simpler way we can accomplish this. We can probably reuse a bunch of the components when we get there... in the meantime let's just keep this PR open and we can revisit again later.

**Comment by Natasha08** [comment]
@nick I completely agree. Implementing search based on DApp1 was quite difficult, and based on @wanderingstan's proposal I'm looking forward to the reimplementation

**Comment by nick** [comment]
Closing this for now. Will revisit later.

**Pull request closed without merging**
