### PR TITLE
Change thumbnail listing to horizontal and overflow scroll bar

### PR DESCRIPTION
**Pull request by ldu2**
- Regarding issue #1727, changing the listing style of the thumbnails
- I simply modified some css to change the style
        -Thumbnails under the main image
        -Overflowing thumbnails with horizontal scroll
But since I am not invited in the Zeplin project, not sure how these two looks like:
       -Navigation arrows on the main image (shown here)
       -Closeable lightbox expansion of main image on click (shown here)
So I didn't attempt that.
This is how it looks like now:
Screenshot_2019-04-29 Zinc House - Origin
Let me know if anything.

### CODE REVIEW

**Comment by micahalcorn** [comment]
Thanks @ldu2 🙏 Can you remove the horizontal margin on the thumbnails container? Since it's no longer being displayed vertically, the margin causes it to be unnecessarily narrow. Ideally, we would also reduce remove the left padding on the first image and the right padding on the last image so that their edges align with the main image.

**Comment by ldu2** [comment]
I have removed the margin on both sides and padding on first and last images on left and right side, correspondingly. Sorry for the multiple commit. I was getting used to the formatting tools. Anyway, this is how it looks like now:
Screenshot from 2019-05-01 16-33-04

**Comment by micahalcorn** [comment]
@ldu2 that looks good, but I think you should be able to accomplish the with just CSS. Want to take another stab at that? 🙂

**Comment by ldu2** [comment]
Yeap. You are right. The CSS version is up there now. Let me know if anything. Appreciate the feedback.

**Comment by micahalcorn** [comment]
Great, thanks 👍 I've also added you to the GitHub organization so that you can push a branch directly to our monorepo in the future. That will allow for CI tests to run and avoid the need for a fork.

**Pull request merged**
