### PR TITLE
remove expiry field from listing

### PR DESCRIPTION
**Pull request by sparrowDom**
### Description:
Removes `expiry` field from listing model. 

### Checklist:

- [x] Test your work and double-check to confirm that you didn't break anything
- ~[ ] Wrap any new text/strings for translation~
- ~[ ] Map any new environment variables with a default value in the Webpack config~
- ~[ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/origin-docs)~

### CODE REVIEW

**Comment by sparrowDom** [comment]
@franckc @jordajm @wanderingstan any objections to removing this field?

**Comment by cuongdo** [comment]
What effect will this have on existing prod listings that will still have the `expiry` field? Will they continue to work, or will they fail to load because of schema validation?

**Comment by sparrowDom** [comment]
@cuongdo good thinking. Seems that the listing validation only checks for presence of fields and field types and doesn't fail when there is an unexpected field. 

Just to be sure have just tested this with creating default listings with `origin-js` fixtures on master  branch(with `expiry` field) and then checked if they load/display on this branch and they do.

**Comment by jordajm** [comment]
What's the motivation for removing the field? I could see it potentially being useful - for example, if a dapp is selling tickets to events, they might choose to set the expiry to the date of the event and then set up their search engine to ignore listings with expiry dates in the past.

**Comment by cuongdo** [comment]
@jordajm brings up a good point. Also, I think that we want listings expiring at some point to ensure that each version of the marketplace contract has a finite lifespan. We don't have any mechanism for porting listings from an older version of the marketplace contract to a newer one, and it'll become cost-prohibitive to support contracts that are too old.

**Comment by sparrowDom** [comment]
@jordajm @cuongdo those are both good points.

The motivation for removing it was solely that it isn't used by anything / populated at listing create time at the moment. If we are ok with having partly implemented feature, that we are pretty sure that it is going to be used in the future, we can cancel this PR. 

The downside is that there is slight engineering overhead supporting expiry in the codebase.

**Comment by franckc** [comment]
Good points on both sides.
Personally I'd vote for cleaning this up and implementing it across our stack when we are ready.
If we leave the code in, then let's add comments so that people are not falsely under the impression that this field is currently supported (it is for future).
Let's bring it up and make decision during the eng weekly.

**Comment by sparrowDom** [comment]
@franckc when you have a minute this is ready to be stamped and merged

**Comment by franckc** [comment]
@sparrowDom Looks like there are a few conflicts with master. Could you hep resolving them then I'll merge. Thank you :)

**Comment by sparrowDom** [comment]
FIxed, just waiting for the tests to pass.

**Comment by sparrowDom** [comment]
@franckc all green here

**Pull request merged**
