### PR TITLE
Added note on how to start over with docker to DEVELOPMENT.md

### PR DESCRIPTION
**Pull request by mikeshultz**
### Description:

When you want to burn docker to the ground and start fresh.

### Checklist:

- [ ] Test your work and double-check to confirm that you didn't break anything
- [ ] [Wrap any new text/strings with `fbt`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#wrapping-text) for translation
- [ ] If there are any new/changed strings to translate, [`npm run translate`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#integrating-translations)
- [ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/docs)

### CODE REVIEW

**Comment by tomlinton** [comment]
The command in the section before (`docker system prune --volumes --all`) does the same thing (without the build bit), but it isn't clear from the text what it does, maybe we can roll these into a single section? Or just replace it with your new command.

**Comment by mikeshultz** [comment]
Yeah, I didn't want to break up that section specific to Mac.  I'll try to rewrite them both to cover the use cases, or maybe combine them into a couple of sub-sections.

**Comment by tomlinton** [comment]
Great, feel free to leave it for later if you want as this is good for now.

**Comment by sparrowDom** [comment]
My docker disk usage steadily grows over time even if I clear all the containers, volumes, images and networks. Do you guys also experience this? 

Currently I am on 112GB Docker disk usage. Each time a `docker down` is ran Docker on my Mac for some reason isn't able to recover that space.

To completely start over and reclaim disk space I also run: 
```
rm -rf ~/Library/Containers/com.docker.docker/Data/*
```

And restart Docker after that

**Comment by mikeshultz** [comment]
@sparrowDom Nope. Right now I'm sitting at 11G, having pruned on Friday.

**Comment by sparrowDom** [comment]
I must be lucky then :)
Screenshot 2019-07-08 17 21 21

**Comment by tomlinton** [comment]
@sparrowDom make sure you stop all containers using docker-compose down or the prune command won’t delete anything.

**Comment by sparrowDom** [comment]
I think when listing containers, volumes and networks I got back an empty list after the prune... but this has been some time ago and I could be wrong

**Comment by mikeshultz** [comment]
I made a minor change, but still think the part about disk space is warranted separately from cleaning house entirely.  Gonna merge this.

**Pull request merged**
