### PR TITLE
Update walletType resolver to detect imToken

### LINKED ISSUE #3212: Misleading Wallet Vendor Name
In IMToken, we are referring to MetaMask. I believe that there is a flag `isMetaMask` on the web3 provider. So unless that is `true`, we should default to something generic like "your wallet". That said, we should detect IMToken, specifically, if possible.

IMG_7585
IMG_4485

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

### PR DESCRIPTION
**Pull request by shahthepro**
Added a check to detech imToken wallet. Fixes #3212 

[Relevant Doc](https://docs.token.im/dapp-sdk/en/)

### CODE REVIEW

**Comment by sparrowDom** [comment]
Fixes some linter things, though it is not completely fine. The update to prettier yesterday broke linter. 

@franckc I have double checked the November campaign descriptions, and 2 were off in the Slife spreadsheet. Have also updated that. Could you update the campaign on prod please?

**Comment by sparrowDom** [comment]
@shahthepro sorry for fixing the growth stuff in this branch. Was just kind of convenient since the Growth tests have been failing here.

**Comment by franckc** [comment]
Thanks @shah and @sparrowDom - I'll deploy this to prod and update the campaign rules...

**Comment by franckc** [comment]
Deployed to prod and updated rules. LGTM. Thanks everyone.

**Pull request merged**
