### PR TITLE
[WIP] IPFS Hash validation for identity events

### PR DESCRIPTION
**Pull request by mikeshultz**
### Description:

adds IPFS hash validation to identity event processing.  I guess we got our first garbage identity update event?

Ref #3581

### Checklist:

- [ ] Test your work and double-check to confirm that you didn't break anything
- [ ] [Wrap any new text/strings with `fbt`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#wrapping-text) for translation
- [ ] If there are any new/changed strings to translate, [`npm run translate`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#integrating-translations)
- [ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/docs)

### CODE REVIEW

**Comment by mikeshultz** [comment]
This is wrong, the `1220` prefix won't come out of a `bytes32` word from an event.  And to boot, pretty much any `bytes32` can be a valid IPFS hash.  I'm not sure if there's any real validation we can do here other than attempting to fetch a file.

We can maybe look for a bunch of zero padding, which is exceedingly unlikely in a hash, but I'm not sure what the real odds are there...

**Comment by mikeshultz** [comment]
Do not merge this

**Comment by nick** [comment]
Sure. FYI marking the PR as WIP when you create it will disable the merge button

**Comment by mikeshultz** [comment]
Yeah, my brain was mush when I initially created it and thought it was good to go.  Don't think there's a way to move back to draft.

**Pull request closed without merging**
