### PR TITLE
[Growth] Fixes and tests for social share/follow rules

### PR DESCRIPTION
**Pull request by franckc**
### Description:
- Misc small fixes to the SocialShare rule logic
- Added TwitterFollow rule to the August campaign
- Update growth graphql schema to return extra metadata that the DApp needs to display the TwitterFollow action
- Updated some unit tests

### Checklist:

- [X] Test your work and double-check to confirm that you didn't break anything
- [ ] [Wrap any new text/strings with `fbt`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#wrapping-text) for translation
- [ ] If there are any new/changed strings to translate, [`npm run translate`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#integrating-translations)
- [ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/docs)

### CODE REVIEW

**Comment by franckc** [comment]
@shahthepro FYI this is what I'm working on so that we don't overlap...

**Comment by shahthepro** [comment]
@franckc I did add a dummy `TwitterFollow` rule to July campaigns for working with the DApp but I've no intent of committing that though.

**Comment by franckc** [comment]
@shahthepro I don't want you to be blocked and having to use temporary code for testing the front-end. So I'm going to land this without waiting for your review. Please do review though and either let me know any change you think I should make or feel free to add/edit yourself this code. Let's iterate ! :)

**Comment by shahthepro** [comment]
Thanks @franckc. I'll have the frontend PR as soon as possible.

**Comment by shahthepro** [comment]
One minor nit. You missed to add `TwitterFollow` to `infra/growth/src/enums.js`.

**Comment by franckc** [comment]
Ah thanks!  To which enum exactly though ? I think infra/growth/src/enum.js:GrowthActionType is deprecated and not used anymore (I should clean it). It is the one you are referring to ?

**Comment by shahthepro** [comment]
@franckc Yes, that was the one I referred to. Just checked and confirmed that it is not used anywhere.

**Pull request merged**
