### PR TITLE
Update Search & Sort UI

### PR DESCRIPTION
**Pull request by shahthepro**
[Link to Test Build](https://originprotocol.github.io/test-builds/shah/#/)

Should address all the comments in issues #3022 and #3021 

### Checklist:

- [x] Test your work and double-check to confirm that you didn't break anything
- [x] [Wrap any new text/strings with `fbt`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#wrapping-text) for translation
- [x] If there are any new/changed strings to translate, [`npm run translate`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#integrating-translations)
- [x] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/docs)

### CODE REVIEW

**Comment by nick** [comment]
Looking at https://zpl.io/2ZnoNQq seems the default search page should have no # listings and no sort link? cc @micahalcorn

**Comment by micahalcorn** [comment]
Sorry @nick 😕 That was us trying to reconcile the new location icon and it looks like the link got lost in that one. We still need to explore that more before worrying too much about it. Regardless, the sort link should remain, thanks.

**Comment by micahalcorn** [comment]
@shahthepro as @nick points out, the number of results should not appear in the initial state.

Also:

- [ ] When filtering by category OR searching, the back link needs some top margin.
- [ ] When filtering by Rewards category, the back link is styled incorrectly.
- [ ] Replace the checkmark icon when @auregimon exports it.
- [ ] Change "< Back to home" to "< Back".

Slightly related:

- [ ] Can we condition the back link in listing detail to only appear in our app as we do here?

**Comment by nick** [comment]
Pushed a test build to https://originprotocol.github.io/test-builds/shah/origin.html

**Comment by shahthepro** [comment]
@nick Thanks for making those changes.

@micahalcorn I have updated the image and made the rest of the changes from your comment. Also, have [updated the test build](https://originprotocol.github.io/test-builds/shah). Check it out and let me know

**Comment by nick** [comment]
Merged for now. Can make any further changes in another PR...

**Pull request merged**
