### PR TITLE
Add missing ATTESTATION_ACCOUNT to dotenv files

### PR DESCRIPTION
**Pull request by franckc**
### Description:

Checked for env files missing ATTESTATION_ACCOUNT and the only one I found was dot.env in origin-linker. @micahalcorn Did you find other places it was missing ?

### Checklist:

- [ ] Test your work and double-check to confirm that you didn't break anything
- [ ] Wrap any displayed ETH addresses with [`formattedAddress`](https://github.com/OriginProtocol/origin/blob/master/origin-dapp/src/utils/user.js#L15-L17)
- [ ] Wrap any new text/strings for translation
- [ ] Map any new environment variables with a default value in the Webpack config
- [ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/origin-docs)

### CODE REVIEW

**Comment by micahalcorn** [comment]
@franckc origin-discovery is where it is most truly missed. It seems to be a critical requirement for the listener. Here is what I have in a `.env` there:

```
AFFILIATE_ACCOUNT=0x821aea9a577a9b44299b9c15c88cf3087f3b5544
ARBITRATOR_ACCOUNT=0x0d1d4e623d10f9fba5db95830f7d3839406c6af2
BLOCK_EPOCH=0
DATABASE_URL=postgresql://localhost/discovery
NETWORK_ID=999
IPFS_URL=http://localhost:8080/
WEB3_URL=http://localhost:8545/
```

**Comment by franckc** [comment]
@micahalcorn: where do you get your .env file for event-listener ? I seed mine from https://github.com/OriginProtocol/origin/blob/master/development/envfiles/event-listener.env#L3 which already has ATTESTATION_ACCOUNT

**Comment by micahalcorn** [comment]
@franckc who knows, I've had it for years. Should we add a origin-discovery/dev.env like we have for the others or no?

**Comment by franckc** [comment]
@micahalcorn I have added dev.env to discovery and listener.

**Pull request merged**
