### PR TITLE
Linking server deployment

### PR DESCRIPTION
**Pull request by tomlinton**
First pull request? Read our [guide to contributing](http://docs.originprotocol.com/#contributing)

### Description:

This is the Kubernetes/Docker config for the mobile linking server.

@crazybuster and @micah I need to sync up with you to get some APNS environment variables. I've set this up in EnvKey.

### Checklist:

- [x] Test your work and double-check to confirm that you didn't break anything
- [ ] ~~Wrap any displayed ETH addresses with [`formattedAddress`](https://github.com/OriginProtocol/origin/blob/master/origin-dapp/src/utils/user.js#L15-L17)~~
- [ ] ~~Wrap any new text/strings for translation~~
- [ ] ~~Map any new environment variables with a default value in the Webpack config~~
- [ ] ~~Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/origin-docs)~~

### CODE REVIEW

**Comment by micah** [comment]
Tom Linton <notifications@github.com> writes:

> @crazybuster and @micah I need to sync up with you to get some APNS
> environment variables. I've set this up in EnvKey.

pretty sure you are intending to notify a different micah here.

**Comment by micahalcorn** [comment]
@micah haha, sorry 😁 Life must be rough with an OG handle, eh @nick?

**Comment by tomlinton** [comment]
No I had it right. We have one micah and he is really good, so I thought I'd try summoning other random micah's to help out :grin:

**Comment by micah** [comment]
Tom Linton <notifications@github.com> writes:

> Merged #1140 into master.

glad I could help!

**Pull request merged**
