### PR TITLE
Add an InviteInfo endpoint to growth server

### PR DESCRIPTION
**Pull request by franckc**
### Description:

Add an InviteInfo endpoint to growth server.
This is to be used on the [referral landing page](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5c50baa43c692ebf5cd87ad5).

### Checklist:

- [ ] Test your work and double-check to confirm that you didn't break anything
- [ ] Wrap any displayed ETH addresses with [`formattedAddress`](https://github.com/OriginProtocol/origin/blob/master/origin-dapp/src/utils/user.js#L15-L17)
- [ ] Wrap any new text/strings for translation
- [ ] Run `npm run translations` if there are any changes to translated strings
- [ ] Map any new environment variables with a default value in the Webpack config
- [ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/origin-docs)

### CODE REVIEW

**Comment by franckc** [comment]
Good question @sparrowDom ! Thanks for your always thorough reviews :)
Yes, I agree in the future it would be cleaner to have an identity service. For now, since we have a single DB where all the tables are located, and since our data model and graphql interfaces are still evolving rapidly, I would vote for keeping things simple. The other thing is it could make sense perhaps to have an origin-identity package. 
For the purpose of this PR, are you ok if I add a TODO and lad as is ?

**Comment by franckc** [comment]
Added TODO.

**Comment by sparrowDom** [comment]
Sure, a TODO is fine. We can always separate that in the future if need be 👍

**Comment by franckc** [comment]
Sounds good. Added TODO. Will land this if you are ok.

**Pull request merged**
