### PR TITLE
Add support for multi-units in perf mode

### PR DESCRIPTION
**Pull request by franckc**
### Description:
Update getOffers logic to work in performance mode:
 - offers data is fetched either from discovery or blockchain based on perf. mode setting
 - filtering of invalid offers is subsequently applied in both cases

### Checklist:

- [X] Test your work and double-check to confirm that you didn't break anything
- [ ] Wrap any new text/strings for translation
- [ ] Map any new environment variables with a default value in the Webpack config
- [ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/origin-docs)

### CODE REVIEW

**Comment by sparrowDom** [comment]
Just wanted to raise a point (not related to the code of this PR) since we are filtering out the invalid offers (not enough unitsAvailable to satisfy offers) users of invalid offers are probably not going to be able to cancel those offers?

**Comment by cuongdo** [comment]
@sparrowDom Offers with enough `unitsAvailable` at the time of the offer should be fine, because we [prevent updates of listings that would make unitsAvailable go negative](https://github.com/OriginProtocol/origin/blob/master/origin-js/src/resources/marketplace.js#L392).

**Comment by sparrowDom** [comment]
@cuongdo yup I agree that edge case is not a problem. I was thinking of another edge case @franckc mentioned the last time we were speaking, and that is if 2 users make an offer at the same time, and there is only 1 more `unitAvailable`. Both of those offers should be mined (since they were valid at the time of offer creation), but only the first one that gets added to blockchain will be valid in the end.

**Comment by cuongdo** [comment]
@sparrowDom Yes, I believe that is an issue. I had some experimental code in a local branch for fixing that issue. Maybe I'll revive that code.

**Pull request merged**
