### PR TITLE
Relayer: One tx per proxy

### PR DESCRIPTION
**Pull request by mikeshultz**
### Description:

This makes sure the relayer only accepts one pending transaction per proxy contract.  It's a short-term solution to prevent bad nonces for #2631.

I'm not really sure if this gels with the behavior of the dapp with profile updates. @nick?

### Checklist:

- [x] Test your work and double-check to confirm that you didn't break anything
- [ ] [Wrap any new text/strings with `fbt`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#wrapping-text) for translation
- [ ] If there are any new/changed strings to translate, [`npm run translate`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#integrating-translations)
- [ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/docs)

### CODE REVIEW

**Comment by nick** [comment]
It's true the dapp would then try to get the user to pay gas... though we can force a hard error in this case. The dapp should never be in a state where a tx hasn't been mined already before attempting another tx though.

**Comment by mikeshultz** [comment]
Does the dapp send using proxies as well?  That's the only way there'd be a nonce conflict.  If it falls back to their normal account it should go through fine.  Though it could still have unintended consequences that maybe the dapp should handle if it gets this error.

**Comment by nick** [comment]
The dapp sends using proxies too, yea

**Comment by mikeshultz** [comment]
Also, would it beneficial to the dapp if this returned the pending tx hash, or is this something that should already be known?

**Pull request merged**
